//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradersToolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradersToolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string BUY {
            get {
                return ResourceManager.GetString("BUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Limit.
        /// </summary>
        internal static string BUY_LIMIT {
            get {
                return ResourceManager.GetString("BUY_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Stop.
        /// </summary>
        internal static string BUY_STOP {
            get {
                return ResourceManager.GetString("BUY_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TradeToolInfo.
        /// </summary>
        internal static string DB_NAME {
            get {
                return ResourceManager.GetString("DB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        internal static string LONG {
            get {
                return ResourceManager.GetString("LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACE.
        /// </summary>
        internal static string PLACE {
            get {
                return ResourceManager.GetString("PLACE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=Edge&quot; /&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;script src=&quot;../bin/Release/plotly/dist/plotly.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;title&gt;Plotly&lt;/title&gt;
        ///    &lt;script&gt;
        ///        document.oncontextmenu = function (e) {
        ///            return false;
        ///        }
        ///    &lt;/script&gt;
        ///
        ///    &lt;style&gt;
        ///        html {
        ///            height: 100%;
        ///            width: 100%;
        ///        }
        ///
        ///        body {
        ///            h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlotlyHomePage {
            get {
                return ResourceManager.GetString("PlotlyHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=Edge&quot; /&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;script src=&quot;../bin/Release/plotly/dist/plotly.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;title&gt;Plotly&lt;/title&gt;
        ///    &lt;script&gt;
        ///        document.oncontextmenu = function (e) {
        ///            return false;
        ///        }
        ///    &lt;/script&gt;
        ///
        ///    &lt;style&gt;
        ///        html {
        ///            height: 100%;
        ///            width: 100%;
        ///        }
        ///
        ///        body {
        ///            h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlotlyHomePage_dark {
            get {
                return ResourceManager.GetString("PlotlyHomePage_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import math, csv, random
        ///import datetime as dt
        ///import numpy as np
        ///import pandas as pd
        ///import talib
        ///
        ///## ------------------------------------------------
        ///##  DEFAULT VARIABLES (do not delete them)
        ///##
        ///file_name_base = &quot;c:\\ESRaw.txt&quot;
        ///file_name_market2 = None
        ///file_name_market3 = None
        ///file_name_Vix = None
        ///start = dt.datetime(2010,1,1)
        ///stop  = dt.datetime(2011,1,1)
        ///df1, df2, df3, dfV = None, None, None, None
        ///
        ///## ------------------------------------------------
        ///##  Read data
        ///##
        ///def ReadData():
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PythonTemplate {
            get {
                return ResourceManager.GetString("PythonTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        internal static string SELL {
            get {
                return ResourceManager.GetString("SELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Limit.
        /// </summary>
        internal static string SELL_LIMIT {
            get {
                return ResourceManager.GetString("SELL_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Stop.
        /// </summary>
        internal static string SELL_STOP {
            get {
                return ResourceManager.GetString("SELL_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        internal static string SHORT {
            get {
                return ResourceManager.GetString("SHORT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group;Key;Text;codeEL;codeNT;codePython;codePRT
        ///Default;Cnot0;Close not zero;close[0] &lt;&gt; 0;Close[0] != 0;C[-1] != 0;close[0] &lt;&gt; 0
        ///Day Of Week;Monday;Monday;dayOfWeek(date) = 1;Time[0].DayOfWeek == DayOfWeek.Monday;data[stocks[0]].datetime.weekday() == 0;dayofweek = 1
        ///Day Of Week;Tuesday;Tuesday;dayOfWeek(date) = 2;Time[0].DayOfWeek == DayOfWeek.Tuesday;data[stocks[0]].datetime.weekday() == 1;dayofweek = 2
        ///Day Of Week;Wednesday;Wednesday;dayOfWeek(date) = 3;Time[0].DayOfWeek == DayOfWeek.Wednesday;data[s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SignalsDescription {
            get {
                return ResourceManager.GetString("SignalsDescription", resourceCulture);
            }
        }
    }
}
