//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradersToolbox.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SimConfigs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SimConfigs"]));
            }
            set {
                this["SimConfigs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal MCDD_Iterations {
            get {
                return ((decimal)(this["MCDD_Iterations"]));
            }
            set {
                this["MCDD_Iterations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public decimal MCDD_AcctSize {
            get {
                return ((decimal)(this["MCDD_AcctSize"]));
            }
            set {
                this["MCDD_AcctSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal VT_Iterations {
            get {
                return ((decimal)(this["VT_Iterations"]));
            }
            set {
                this["VT_Iterations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal VT_Trades {
            get {
                return ((decimal)(this["VT_Trades"]));
            }
            set {
                this["VT_Trades"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public decimal VT_Variations {
            get {
                return ((decimal)(this["VT_Variations"]));
            }
            set {
                this["VT_Variations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public decimal VT_Ruin {
            get {
                return ((decimal)(this["VT_Ruin"]));
            }
            set {
                this["VT_Ruin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public decimal MCE_ToPick {
            get {
                return ((decimal)(this["MCE_ToPick"]));
            }
            set {
                this["MCE_ToPick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal MCE_Iterations {
            get {
                return ((decimal)(this["MCE_Iterations"]));
            }
            set {
                this["MCE_Iterations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal MCE_Lower {
            get {
                return ((decimal)(this["MCE_Lower"]));
            }
            set {
                this["MCE_Lower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public decimal MCE_Upper {
            get {
                return ((decimal)(this["MCE_Upper"]));
            }
            set {
                this["MCE_Upper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double ResultsWindowWidth {
            get {
                return ((double)(this["ResultsWindowWidth"]));
            }
            set {
                this["ResultsWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1900-01-01")]
        public global::System.DateTime DataVersionDate {
            get {
                return ((global::System.DateTime)(this["DataVersionDate"]));
            }
            set {
                this["DataVersionDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomStrategies {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomStrategies"]));
            }
            set {
                this["CustomStrategies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public decimal NoiseTestOpen {
            get {
                return ((decimal)(this["NoiseTestOpen"]));
            }
            set {
                this["NoiseTestOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public decimal NoiseTestLow {
            get {
                return ((decimal)(this["NoiseTestLow"]));
            }
            set {
                this["NoiseTestLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public decimal NoiseTestHigh {
            get {
                return ((decimal)(this["NoiseTestHigh"]));
            }
            set {
                this["NoiseTestHigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public decimal NoiseTestClose {
            get {
                return ((decimal)(this["NoiseTestClose"]));
            }
            set {
                this["NoiseTestClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public decimal NoiseTestMax {
            get {
                return ((decimal)(this["NoiseTestMax"]));
            }
            set {
                this["NoiseTestMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal NoiseTestCount {
            get {
                return ((decimal)(this["NoiseTestCount"]));
            }
            set {
                this["NoiseTestCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyName {
            get {
                return ((string)(this["ProxyName"]));
            }
            set {
                this["ProxyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyPassword {
            get {
                return ((string)(this["ProxyPassword"]));
            }
            set {
                this["ProxyPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VsOther1Symbol {
            get {
                return ((string)(this["VsOther1Symbol"]));
            }
            set {
                this["VsOther1Symbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VsOther2Symbol {
            get {
                return ((string)(this["VsOther2Symbol"]));
            }
            set {
                this["VsOther2Symbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VsOther3Symbol {
            get {
                return ((string)(this["VsOther3Symbol"]));
            }
            set {
                this["VsOther3Symbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TTmaxPNLEnabled {
            get {
                return ((bool)(this["TTmaxPNLEnabled"]));
            }
            set {
                this["TTmaxPNLEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal TTmaxPNLstart {
            get {
                return ((decimal)(this["TTmaxPNLstart"]));
            }
            set {
                this["TTmaxPNLstart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal TTmaxPNLend {
            get {
                return ((decimal)(this["TTmaxPNLend"]));
            }
            set {
                this["TTmaxPNLend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal TTmaxPNLstep {
            get {
                return ((decimal)(this["TTmaxPNLstep"]));
            }
            set {
                this["TTmaxPNLstep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TTminPNLenabled {
            get {
                return ((bool)(this["TTminPNLenabled"]));
            }
            set {
                this["TTminPNLenabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal TTminPNLstart {
            get {
                return ((decimal)(this["TTminPNLstart"]));
            }
            set {
                this["TTminPNLstart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal TTminPNLend {
            get {
                return ((decimal)(this["TTminPNLend"]));
            }
            set {
                this["TTminPNLend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal TTminPNLstep {
            get {
                return ((decimal)(this["TTminPNLstep"]));
            }
            set {
                this["TTminPNLstep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TTmaxTradesEnabled {
            get {
                return ((bool)(this["TTmaxTradesEnabled"]));
            }
            set {
                this["TTmaxTradesEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal TTmaxTradesStart {
            get {
                return ((decimal)(this["TTmaxTradesStart"]));
            }
            set {
                this["TTmaxTradesStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal TTmaxTradesEnd {
            get {
                return ((decimal)(this["TTmaxTradesEnd"]));
            }
            set {
                this["TTmaxTradesEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal TTmaxTradesStep {
            get {
                return ((decimal)(this["TTmaxTradesStep"]));
            }
            set {
                this["TTmaxTradesStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TTstartTimeEnabled {
            get {
                return ((bool)(this["TTstartTimeEnabled"]));
            }
            set {
                this["TTstartTimeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-01-01")]
        public global::System.DateTime TTstartTimeStart {
            get {
                return ((global::System.DateTime)(this["TTstartTimeStart"]));
            }
            set {
                this["TTstartTimeStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-01-01")]
        public global::System.DateTime TTstartTimeEnd {
            get {
                return ((global::System.DateTime)(this["TTstartTimeEnd"]));
            }
            set {
                this["TTstartTimeEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2020 01:00:00")]
        public global::System.DateTime TTstartTimeStep {
            get {
                return ((global::System.DateTime)(this["TTstartTimeStep"]));
            }
            set {
                this["TTstartTimeStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TTendTimeEnabled {
            get {
                return ((bool)(this["TTendTimeEnabled"]));
            }
            set {
                this["TTendTimeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-01-01")]
        public global::System.DateTime TTendTimeStart {
            get {
                return ((global::System.DateTime)(this["TTendTimeStart"]));
            }
            set {
                this["TTendTimeStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-01-01")]
        public global::System.DateTime TTendTimeEnd {
            get {
                return ((global::System.DateTime)(this["TTendTimeEnd"]));
            }
            set {
                this["TTendTimeEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2020 01:00:00")]
        public global::System.DateTime TTendTimeStep {
            get {
                return ((global::System.DateTime)(this["TTendTimeStep"]));
            }
            set {
                this["TTendTimeStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TTaddCode {
            get {
                return ((bool)(this["TTaddCode"]));
            }
            set {
                this["TTaddCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int DatabaseUpdatePeriod {
            get {
                return ((int)(this["DatabaseUpdatePeriod"]));
            }
            set {
                this["DatabaseUpdatePeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnsVisibility {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnsVisibility"]));
            }
            set {
                this["ColumnsVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2020 17:00:00")]
        public global::System.DateTime IntraEndOfDay {
            get {
                return ((global::System.DateTime)(this["IntraEndOfDay"]));
            }
            set {
                this["IntraEndOfDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IntraSymbol {
            get {
                return ((string)(this["IntraSymbol"]));
            }
            set {
                this["IntraSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IntraExcludeExits {
            get {
                return ((bool)(this["IntraExcludeExits"]));
            }
            set {
                this["IntraExcludeExits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FavoriteSignals {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FavoriteSignals"]));
            }
            set {
                this["FavoriteSignals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentConfigFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentConfigFiles"]));
            }
            set {
                this["RecentConfigFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SignalsXML {
            get {
                return ((string)(this["SignalsXML"]));
            }
            set {
                this["SignalsXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomSignalsXML {
            get {
                return ((string)(this["CustomSignalsXML"]));
            }
            set {
                this["CustomSignalsXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TradeStationRefreshToken {
            get {
                return ((string)(this["TradeStationRefreshToken"]));
            }
            set {
                this["TradeStationRefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public double MainWindowWidth {
            get {
                return ((double)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("750")]
        public double MainWindowHeight {
            get {
                return ((double)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double ResultsWindowHeight {
            get {
                return ((double)(this["ResultsWindowHeight"]));
            }
            set {
                this["ResultsWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("950")]
        public double SimTaskWindowWidth {
            get {
                return ((double)(this["SimTaskWindowWidth"]));
            }
            set {
                this["SimTaskWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double SimTaskWindowHeight {
            get {
                return ((double)(this["SimTaskWindowHeight"]));
            }
            set {
                this["SimTaskWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double MainWindowTop {
            get {
                return ((double)(this["MainWindowTop"]));
            }
            set {
                this["MainWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double MainWindowLeft {
            get {
                return ((double)(this["MainWindowLeft"]));
            }
            set {
                this["MainWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowState {
            get {
                return ((int)(this["MainWindowState"]));
            }
            set {
                this["MainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double TextOutWindowWidth {
            get {
                return ((double)(this["TextOutWindowWidth"]));
            }
            set {
                this["TextOutWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double TextOutWindowHeight {
            get {
                return ((double)(this["TextOutWindowHeight"]));
            }
            set {
                this["TextOutWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("750")]
        public double GraphWindowWidth {
            get {
                return ((double)(this["GraphWindowWidth"]));
            }
            set {
                this["GraphWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double GraphWindowHeight {
            get {
                return ((double)(this["GraphWindowHeight"]));
            }
            set {
                this["GraphWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("630")]
        public double HistogramWindowHeight {
            get {
                return ((double)(this["HistogramWindowHeight"]));
            }
            set {
                this["HistogramWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double HistogramWindowWidth {
            get {
                return ((double)(this["HistogramWindowWidth"]));
            }
            set {
                this["HistogramWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("650")]
        public double BreakdownWindowWidth {
            get {
                return ((double)(this["BreakdownWindowWidth"]));
            }
            set {
                this["BreakdownWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public double BreakdownWindowHeight {
            get {
                return ((double)(this["BreakdownWindowHeight"]));
            }
            set {
                this["BreakdownWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public double RandomOOSWindowWidth {
            get {
                return ((double)(this["RandomOOSWindowWidth"]));
            }
            set {
                this["RandomOOSWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double RandomOOSWindowHeight {
            get {
                return ((double)(this["RandomOOSWindowHeight"]));
            }
            set {
                this["RandomOOSWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double GraphStockWindowWidth {
            get {
                return ((double)(this["GraphStockWindowWidth"]));
            }
            set {
                this["GraphStockWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public double GraphStockWindowHeight {
            get {
                return ((double)(this["GraphStockWindowHeight"]));
            }
            set {
                this["GraphStockWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double GraphLast15WindowWidth {
            get {
                return ((double)(this["GraphLast15WindowWidth"]));
            }
            set {
                this["GraphLast15WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double GraphLast15WindowHeight {
            get {
                return ((double)(this["GraphLast15WindowHeight"]));
            }
            set {
                this["GraphLast15WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double FloatingChartWidth {
            get {
                return ((double)(this["FloatingChartWidth"]));
            }
            set {
                this["FloatingChartWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double FloatingChartHeight {
            get {
                return ((double)(this["FloatingChartHeight"]));
            }
            set {
                this["FloatingChartHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SymbolsXML {
            get {
                return ((string)(this["SymbolsXML"]));
            }
            set {
                this["SymbolsXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double CustomStratWindowWidth {
            get {
                return ((double)(this["CustomStratWindowWidth"]));
            }
            set {
                this["CustomStratWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double CustomStratWindowHeight {
            get {
                return ((double)(this["CustomStratWindowHeight"]));
            }
            set {
                this["CustomStratWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double CustomIndicatorsWindowWidth {
            get {
                return ((double)(this["CustomIndicatorsWindowWidth"]));
            }
            set {
                this["CustomIndicatorsWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double CustomIndicatorsWindowHeight {
            get {
                return ((double)(this["CustomIndicatorsWindowHeight"]));
            }
            set {
                this["CustomIndicatorsWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public double SimulatedTradingWindowWidth {
            get {
                return ((double)(this["SimulatedTradingWindowWidth"]));
            }
            set {
                this["SimulatedTradingWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double SimulatedTradingWindowHeight {
            get {
                return ((double)(this["SimulatedTradingWindowHeight"]));
            }
            set {
                this["SimulatedTradingWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string Broker {
            get {
                return ((string)(this["Broker"]));
            }
            set {
                this["Broker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseExtendedHours {
            get {
                return ((bool)(this["UseExtendedHours"]));
            }
            set {
                this["UseExtendedHours"] = value;
            }
        }
    }
}
